### ISSUE TITLE
有些输入的任务，无法复现出想要的效果

### ISSUE THREAD

**Issue by haowuliao** [neukg/TechGPT#1]
根据示例代码：
input_str = """抽取出下面文本的实体和实体类型：
《女人树》，国产电视剧，由导演田迪执导，根据作家子页的原著改编，故事从1947年开始，跨越了解放战争和建国初期两大历史时期，展现了战斗在隐形战线上的人民英雄是如何不惧怕任何危险，不计较个人牺牲，甚至不顾人民内部的误解和生死裁决，都不暴露个人真实身份，至死不渝，与敌人周旋到底的英雄故事。"""
prompt = "Human: {} \n\nAssistant: ".format(input_str)

inputs = tokenizer(prompt, return_tensors="pt")
input_ids = inputs["input_ids"].to(device)
generation_config = GenerationConfig(
    temperature=0.1,
    top_p=0.75,
    top_k=40,
    num_beams=1,
    bos_token_id=1,
    eos_token_id=2,
    pad_token_id=0,
    max_new_tokens=128,
    min_new_tokens=10,
    do_sample=True,
)
with torch.no_grad():
    generation_output = model.generate(
        input_ids=input_ids,
        generation_config=generation_config,
        return_dict_in_generate=True,
        output_scores=True,
        repetition_penalty=1.2,
    )
    output = generation_output.sequences[0]
    output = tokenizer.decode(output, skip_special_tokens=True)
    print(output)

输出：
Human: 抽取出下面文本的实体和实体类型：
《女人树》，国产电视剧，由导演田迪执导，根据作家子页的原著改编，故事从1947年开始，跨越了解放战争和建国初期两大历史时期，展现了战斗在隐形战线上的人民英雄是如何不惧怕任何危险，不计较个人牺牲，甚至不顾人民内部的误解和生死裁决，都不暴露个人真实身份，至死不渝，与敌人周旋到底的英雄故事。 

Assistant: 女人树是一部国产电视剧，其名称为“女人树”。该作品是由导演田迪执导的，改编自作家子页的同名小说。故事发生在1947年至新中国成立期间的历史时期，主要展示了人们如何在战争中表现出英勇无畏的精神和不畏艰险的勇气。
在该剧中，主人公们是那些以自己的生命为代价，保护着其他人的英雄人物。他们并不考虑个人的利益或安全，而是为了保卫家园、捍卫正义而奋斗。这些英雄人物包括士兵、医生、护士等，他们在战场上展现出非凡的能力和勇气，成为了人民心中的英雄。
总之，女人树是一部反映中国近代史的重要

像 三元组抽取也存在的这样问题，是不是我的使用方式有问题

**Comment by abel-nlp** [comment]
你好，你得到的输出类似模型未经微调得到的，要不你再检查一下载入模型的checkpoint路径是否正确

**Comment by haowuliao** [comment]
这个，我也确认了一下，载入的模型就是正确解密出来的，我用的llama-7B权重是用pyllama下载的，有影响吗

**Comment by neukg** [comment]
解密后能正常加载就没问题，我们本地也确认了一下，没有出现您提到的这个问题，请确认模型权重、tokenizer以及config是否来源于 https://huggingface.co/neukg/TechGPT-7B
![image](https://github.com/neukg/TechGPT/assets/60178687/c0c16292-18e5-4542-bfc7-b6e99f8d57eb)
