### ISSUE TITLE
我的模型文件 只有pytorch_model.bin MD5值不一样

### ISSUE THREAD

**Issue by oho-work** [neukg/TechGPT#2]
6d5f0d60a6e36ebc1518624a46f5a717  ./config.json
2917a1cafb895cf57e746cfd7696bfe5  ./generation_config.json
d41d8cd98f00b204e9800998ecf8427e  ./pytorch_model.bin
15f7a943faa91a794f38dd81a212cb01  ./special_tokens_map.json
6ffe559392973a92ea28032add2a8494  ./tokenizer.model
08f6f621dba90b2a23c6f9f7af974621  ./tokenizer_config.json

**Comment by neukg** [comment]
可以尝试重新下载，可能是文件较大，下载不完整。
