### ISSUE TITLE
文本类似内容阅读理解认知混乱错误

### ISSUE THREAD

**Issue by Spider4U** [neukg/TechGPT#3]
文本内容人为构造

![techgpt](https://github.com/neukg/TechGPT/assets/39551480/338139d3-abcd-4774-a1fb-37dd47e13cd1)

**Comment by neukg** [comment]
当前开源的7B模型理解能力有限，13B版本有所提升，“上海瑞金医院南门附近有个日月光广场和田和坊”模型会产生误解。

**Comment by Spider4U** [comment]
> 当前开源的7B模型理解能力有限，13B版本有所提升，“上海瑞金医院南门附近有个日月光广场和田和坊”模型会产生误解。

13B版本近期会开源吗
