### ISSUE TITLE
关于模型加载时间过长和超长报错的问题

### ISSUE THREAD

**Issue by Dojay6103** [neukg/TechGPT#8]
大模型和知识图谱结合新手一枚，感觉生成效果还是不错的。
在使用示例代码调用模型抽取关键词的时候发现模型加载后运算出结果是很快的，但是加载模型的过程非常慢，请问能否优化？
另外在文本过长后会超出当前显存，请教一下有没有什么解决方案？

**Comment by Asimok** [comment]
推荐使用40g以上显存的设备部署
