### ISSUE TITLE
decrypt过程太久了，有没有加速的办法？

### ISSUE THREAD

**Issue by evelynxyx** [neukg/TechGPT#9]
decrypt过程起码要4个小时，为什么要这么设置呢？中间很容易出错啊，这个过程需要GPU还是CPU，有没有加速或者直接拿到模型文件的办法

**Comment by Asimok** [comment]
- llama协议限制，没有提供解密权重的许可，因此确保您有llama权重的使用权限，我们使用加密的方式验证。
- 解密需要cpu算力支持，可以多进程实现加速解密。
